# SQL

In [3]:
import pandas as pd
import sqlite3

## 1

In [ ]:
# 1. Leer el archivo Excel
sales_df = pd.read_excel("Base de datos BI.xlsx", sheet_name="Sales")
product_df = pd.read_excel("Base de datos BI.xlsx", sheet_name="Product")
customer_df = pd.read_excel("Base de datos BI.xlsx", sheet_name="Customers")
geography_df = pd.read_excel("Base de datos BI.xlsx", sheet_name="Geography")

In [15]:
# 2. Crear conexión a base de datos SQLite
conn = sqlite3.connect("mi_base.db")

In [16]:
# 3. Guardar DataFrame como tabla SQL
sales_df.to_sql("sales", conn, if_exists="replace", index=False)
product_df.to_sql("product", conn, if_exists="replace", index=False)   
customer_df.to_sql("customer", conn, if_exists="replace", index=False)
geography_df.to_sql("geography", conn, if_exists="replace", index=False)

655

In [20]:
# 4. Hacer una consulta SQL
query = """
SELECT geography.City, product.ProductName, COUNT(sales.ProductKey) AS ventas
FROM product
    INNER JOIN sales ON product.ProductK = sales.ProductKey
    INNER JOIN customer ON sales.CustomerKey = customer.Customer_Key
    INNER JOIN geography ON customer.Geography = geography.GeographyKey
GROUP BY geography.City
ORDER BY ventas DESC
"""

resultado = pd.read_sql_query(query, conn)

print("\nResultado de la consulta:")
print(resultado)

Resultado de la consulta:
            City                 ProductName  ventas
0         London  Long-Sleeve Logo Jersey, S    1579
1          Paris  Long-Sleeve Logo Jersey, S    1174
2      Cliffside  Long-Sleeve Logo Jersey, S     918
3    Chula Vista  Long-Sleeve Logo Jersey, S     583
4         Berlin  Long-Sleeve Logo Jersey, S     583
..           ...                         ...     ...
264     Chehalis       Water Bottle - 30 oz.       1
265        Byron       Water Bottle - 30 oz.       1
266    Braintree      Mountain-200 Black, 42       1
267     Bellevue      Mountain-200 Black, 42       1
268      Barstow            Road-150 Red, 52       1

[269 rows x 3 columns]

In [21]:
# 5. Cerrar conexión
conn.close()

## 2

In [ ]:
query = """
SELECT d.department_name, COUNT(e.employee_id) AS empleados
FROM departments d
INNER JOIN employees e ON d.department_id = e.department_id
GROUP BY d.department_name
HAVING empleados < AVG(empleados)
"""

## 4

### A

In [ ]:
query = """
SELECT e.first_name, e.last_name, e.salary, AVG(e.salary) AS salario_promedio
FROM departments d
INNER JOIN employees e ON d.department_id = e.department_id
GROUP BY d.department_name
HAVING e.salary > AVG(salario_promedio)
"""

### B

In [ ]:
query = """
SELECT d.department_name, AVG(e.salary) AS salario_promedio
FROM departments d
INNER JOIN employees e ON d.department_id = e.department_id
WHERE e.manager_id = 1
GROUP BY d.department_name
"""

### C

In [ ]:
query = """
SELECT d.department_name, e.first_name AS nombre, e.last_name AS apellido
FROM departments d
INNER JOIN employees e ON d.department_id = e.department_id
GROUP BY d.department_name
"""

# Python

In [ ]:
# Consideré que cada sección de la prueba es separada, por eso voy a volver a importar las librerías

import pandas as pd

In [ ]:
df = pd.read_csv("customer_data.txt")

## 1

In [ ]:
print(df.head())

   customer_id  age  gender  tenure_months   contract_type  monthly_charges  \
0            1   42  Female             24  Month-to-month            74.35
1            2   28    Male              6  Month-to-month            60.15
2            3   57    Male             36        One year            82.55
3            4   35  Female             12  Month-to-month            55.25
4            5   61  Female             58        Two year            92.85

   total_charges internet_service phone_service multiple_lines  ...  \
0        1788.45      Fiber optic           Yes            Yes  ...
1         371.85      Fiber optic           Yes             No  ...
2        2927.85      Fiber optic           Yes             No  ...
3         671.75              DSL           Yes             No  ...
4        5293.30      Fiber optic           Yes            Yes  ...

  online_backup device_protection tech_support streaming_tv streaming_movies  \
0            No               Yes           No          Yes              Yes
1            No                No           No           No               No
2           Yes                No          Yes          Yes               No
3            No                No           No           No               No
4           Yes               Yes          Yes          Yes              Yes

  paperless_billing             payment_method monthly_usage_gb  \
0               Yes           Electronic check            215.3
1               Yes           Electronic check            134.7
2               Yes    Credit card (automatic)            187.2
3                No  Bank transfer (automatic)             98.4
4               Yes  Bank transfer (automatic)            243.6

   customer_service_calls  churn
0                     1.0     No
1                     0.0    Yes
2                     0.0     No
3                     1.0     No
4                     0.0     No

[5 rows x 21 columns]

In [29]:
print(df.tail())

     customer_id  age  gender  tenure_months   contract_type  monthly_charges  \
139          140   63    Male             56        Two year            99.35
140          141   29  Female              5  Month-to-month            56.95
141          142   45    Male             24        One year            85.15
142          143   54  Female             34        Two year            91.15
143          144   27    Male              3  Month-to-month            54.85

     total_charges internet_service phone_service multiple_lines  ...  \
139        5558.55      Fiber optic           Yes            Yes  ...
140         288.95              DSL           Yes            Yes  ...
141        2047.55      Fiber optic           Yes             No  ...
142        3116.15      Fiber optic           Yes            Yes  ...
143         166.45              DSL           NaN            NaN  ...

    online_backup device_protection tech_support streaming_tv  \
139           Yes               Yes          Yes           No
140            No                No           No           No
141           Yes               Yes           No          Yes
142            No               Yes          Yes          Yes
143           NaN               NaN          NaN          NaN

    streaming_movies paperless_billing             payment_method  \
139              Yes                No  Bank transfer (automatic)
140               No               Yes           Electronic check
141               No               Yes    Credit card (automatic)
142              Yes                No  Bank transfer (automatic)
143              NaN               NaN                        NaN

    monthly_usage_gb  customer_service_calls  churn
139            238.9                     0.0     No
140             87.3                     1.0    Yes
141            201.3                     0.0     No
142            222.9                     1.0     No
143              NaN                     NaN    NaN

[5 rows x 21 columns]

In [30]:
# Tamaño de la base de datos:
df.shape

(144, 21)

In [31]:
# Nombre de las variables:
print(df.columns)

# Tipos de variables:
print(df.dtypes)

Index(['customer_id', 'age', 'gender', 'tenure_months', 'contract_type',
       'monthly_charges', 'total_charges', 'internet_service', 'phone_service',
       'multiple_lines', 'online_security', 'online_backup',
       'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies',
       'paperless_billing', 'payment_method', 'monthly_usage_gb',
       'customer_service_calls', 'churn'],
      dtype='object')
customer_id                 int64
age                         int64
gender                     object
tenure_months               int64
contract_type              object
monthly_charges           float64
total_charges             float64
internet_service           object
phone_service              object
multiple_lines             object
online_security            object
online_backup              object
device_protection          object
tech_support               object
streaming_tv               object
streaming_movies           object
paperless_billing          object
payment_method             object
monthly_usage_gb          float64
customer_service_calls    float64
churn                      object
dtype: object

In [ ]:
df.isna().sum()

customer_id               0
age                       0
gender                    0
tenure_months             0
contract_type             0
monthly_charges           0
total_charges             0
internet_service          0
phone_service             1
multiple_lines            1
online_security           1
online_backup             1
device_protection         1
tech_support              1
streaming_tv              1
streaming_movies          1
paperless_billing         1
payment_method            1
monthly_usage_gb          1
customer_service_calls    1
churn                     1
dtype: int64

In [ ]:
# Ver cuales son los usuarios con NA.
df[df["phone_service"].isna()]

# Solamente hay un usuario con NA, por lo que se eliminará esa fila, 
# esto debido a que también es un usuario con churn NA, entonces no nos servira para clasificar,
# además solo es un usuario, por lo que no será un cambio muy drástico que afecte a toda la base de datos.

,customer_id,age,gender,tenure_months,contract_type,monthly_charges,total_charges,internet_service,phone_service,multiple_lines,...,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,paperless_billing,payment_method,monthly_usage_gb,customer_service_calls,churn
143,144,27,Male,3,Month-to-month,54.85,166.45,DSL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df = df.dropna(subset=["phone_service"])

## 3

In [ ]:
# Simulación de fechas y volumen
import pandas as pd
import numpy as np
from datetime import datetime, timedelta


#FECHAS (Simulación de un año de historial)
end_date = datetime.now()
df['timestamp'] = [end_date - timedelta(days=np.random.randint(0, 365)) for _ in range(len(df))]
df['timestamp'] = pd.to_datetime(df['timestamp'])

#VOLUMEN 
df['transaction_volume'] = (df['monthly_usage_gb'] / 30).astype(int) + 1

#AHT (Tiempo promedio de atención en segundos)
df['actual_aht_sec'] = np.random.randint(200, 500, len(df))

In [41]:
df

,customer_id,age,gender,tenure_months,contract_type,monthly_charges,total_charges,internet_service,phone_service,multiple_lines,...,streaming_tv,streaming_movies,paperless_billing,payment_method,monthly_usage_gb,customer_service_calls,churn,timestamp,transaction_volume,actual_aht_sec
0,1,42,Female,24,Month-to-month,74.35,1788.45,Fiber optic,Yes,Yes,...,Yes,Yes,Yes,Electronic check,215.3,1.0,No,2026-01-17 09:15:29.995394,8,461
1,2,28,Male,6,Month-to-month,60.15,371.85,Fiber optic,Yes,No,...,No,No,Yes,Electronic check,134.7,0.0,Yes,2026-03-20 09:15:29.995394,5,441
2,3,57,Male,36,One year,82.55,2927.85,Fiber optic,Yes,No,...,Yes,No,Yes,Credit card (automatic),187.2,0.0,No,2025-06-21 09:15:29.995394,7,295
3,4,35,Female,12,Month-to-month,55.25,671.75,DSL,Yes,No,...,No,No,No,Bank transfer (automatic),98.4,1.0,No,2026-03-20 09:15:29.995394,4,273
4,5,61,Female,58,Two year,92.85,5293.30,Fiber optic,Yes,Yes,...,Yes,Yes,Yes,Bank transfer (automatic),243.6,0.0,No,2025-06-08 09:15:29.995394,9,476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,139,36,Female,12,Month-to-month,69.95,839.35,Fiber optic,Yes,No,...,Yes,Yes,Yes,Electronic check,179.8,0.0,No,2025-08-28 09:15:29.995394,6,241
139,140,63,Male,56,Two year,99.35,5558.55,Fiber optic,Yes,Yes,...,No,Yes,No,Bank transfer (automatic),238.9,0.0,No,2025-04-03 09:15:29.995394,8,366
140,141,29,Female,5,Month-to-month,56.95,288.95,DSL,Yes,Yes,...,No,No,Yes,Electronic check,87.3,1.0,Yes,2026-03-08 09:15:29.995394,3,214
141,142,45,Male,24,One year,85.15,2047.55,Fiber optic,Yes,No,...,Yes,No,Yes,Credit card (automatic),201.3,0.0,No,2025-11-17 09:15:29.995394,7,330
142,143,54,Female,34,Two year,91.15,3116.15,Fiber optic,Yes,Yes,...,Yes,Yes,No,Bank transfer (automatic),222.9,1.0,No,2026-02-07 09:15:29.995394,8,436

## 4

Se podría utilizar un modelo logístico o un modelo de deeplearnig para poder tener una probabilidad de que un cliente sea un churn o no, si la probabilidad es mayor a 0.5 (50%) el cliente será considerado churn.

In [ ]:
# Se cambiarán los yes por 1 y no por 0